### PR TITLE
chore: cow is the new aave

### PR DESCRIPTION
**Pull request by gosuto-inzasheru**

### CODE REVIEW

**Comment by gosuto-inzasheru** [comment]
deployed and verified on sepolia: https://sepolia.etherscan.io/address/0xD8F39db3789b1aafdFC852d0e0ebC3E4940a88bc#code

successful swap of 8 bal for 4.1 cow on sepolia (from and to same test msig): https://sepolia.etherscan.io/tx/0x9efb05b3fad074777cad38342602d5c8d4f22b3f1918d119051efbad0da5cc57

**Comment by gosuto-inzasheru** [comment]
> Mike B, [2 Dec 2024 at 20:42:30]:
so cow guys got back to me and they asked if we could have it so the destination and source address for cow are different. do you think this is too much? 
>
> Moving this discussion here.
The destination address is: 0x3E2897E71E504B0510Bed7983579280b32ac1CA5
The from address : 0xcA771eda0c70aA7d053aB1B25004559B918FE662

**Comment by fedgiac** [comment]
As of commit b1c504091321192bc2c70ee68aac91ceeb18bbbf, I don't see any issue with using the contract at `contracts/OtcEscrowApprovals.sol` to perform the token swap between CoW DAO and Balancer DAO.

I don't see any relevant [advisories](https://github.com/OpenZeppelin/openzeppelin-contracts/security/advisories), but it would still be nice to bump the OpenZeppelin library to the latest [version with security patches](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/HEAD/SECURITY.md#supported-versions). I wouldn't consider this a blocker though.

**Comment by gosuto-inzasheru** [comment]
thanks @fedgiac! i updated the oz lib (2c3bdd6) and deployed the contract (b25bf0d)!

**Review by mikebmikeb — APPROVED** [review]

**Pull request merged**
